### ISSUE TITLE
Positioning issue

### ISSUE THREAD

**Issue by Voltra** [byeolbit/translucent#2]
Following the guide, I encountered a tiny problem while positioning my element. My example page was really simple so I was worried it could be a general mistake depending on how the containers are positionned
![screenshot_173](https://user-images.githubusercontent.com/25990549/28746120-126ea94c-7486-11e7-94ad-3ea1028e8fef.png)
![screenshot_174](https://user-images.githubusercontent.com/25990549/28746119-126da6e6-7486-11e7-9390-5e2e0d53bba4.png)
![screenshot_175](https://user-images.githubusercontent.com/25990549/28746121-127124d8-7486-11e7-83cc-0efebacc94a7.png)
![screenshot_176](https://user-images.githubusercontent.com/25990549/28746126-2dabe6c0-7486-11e7-860f-1fe5d565d695.png)

**Comment by byeolbit** [comment]
Try insert jQuery-UI inside your html file.
There is no problem with your codes.
I think I forgot to remove some jQuery-UI functions in my plugin. I'll fix it.
