### ISSUE TITLE
"tl-card-contents" position issue in compressed version

### ISSUE THREAD

**Issue by benjenq** [byeolbit/translucent#4]
I've try compressed version & non-compressed version both, and got different result. It seem that a  position bug in compressed version. 

I spend lots of time to check my js/css code with using compressed version , and finally find this issue.

Non-compressed version works fine for me. thx!.
![2018-03-10](https://user-images.githubusercontent.com/11935557/37237884-983c31be-2455-11e8-8056-3c58efbb1933.png)

**Comment by byeolbit** [comment]
Thank you for your report 😄 . I'll patch this problem.

**Comment by byeolbit** [comment]
Fixed at 1.0.11
